env:
  - COSIGN_EXPERIMENTAL=true
builds:
  - id: linux
    binary: tally
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -v
  - id: darwin
    binary: tally
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -v
  - id: windows
    binary: tally
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -v
signs:
  - id: cosign
    cmd: cosign
    certificate: "${artifact}.crt"
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature"
      - "${signature}"
      - "--output-certificate"
      - "${certificate}"
      - "${artifact}"
    artifacts: all
release:
  github:
    owner: jetstack
    name: tally
