env:
  - COSIGN_EXPERIMENTAL=true
builds:
  - id: tally-build
    binary: tally
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -v
signs:
  - id: tally-cosign
    cmd: cosign
    certificate: "${artifact}.crt"
    args: ["sign-blob", "--output-signature", "${signature}", "--output-certificate", "${certificate}", "${artifact}"]
    artifacts: all
release:
  github:
    owner: jetstack
    name: tally
