on:
  schedule:
    # Tuesday at 2AM UTC
    - cron: "0 2 * * 2"
  workflow_dispatch:

env:
  GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/998629990322/locations/global/workloadIdentityPools/tally-db-creator/providers/tally-db-creator"
  GCP_SERVICE_ACCOUNT: "tally-db-creator@jetstack-rob-best.iam.gserviceaccount.com"
  GCP_PROJECT_ID: "jetstack-rob-best"
  REGISTRY: ghcr.io

jobs:
  create-db:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Google Cloud auth
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Log into ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          cache: true

      - name: Create DB
        # TODO: use an actual released version of the application here
        run: go run ./... db create --project-id ${{ env.GCP_PROJECT_ID }}

      - name: Push DB
        working-directory: /home/runner/.cache/tally/db
        run: |
          zstd -k -19 tally.db
          oras push ${{ env.REGISTRY }}/${{ github.repository }}/db:latest metadata.json:application/vnd.jetstack.tally.metadata.layer.v1 tally.db.zst:application/vnd.jetstack.tally.db.layer.v1+zstd
