name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install cosign
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ko:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      COSIGN_EXPERIMENTAL: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: true

      - name: Setup ko
        uses: imjasonh/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa

      - name: Install cosign
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9

      - name: Login to ghcr.io
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build
        run: |
          ko build \
            --bare \
            -t latest \
            -t ${{ github.ref_name }} \
            --platform=linux/amd64,linux/arm64,linux/arm \
            --sbom=cyclonedx \
            --image-refs image-refs.txt
          cosign sign --yes $(cat image-refs.txt)
