name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache: true

      - name: Download
        run: go mod download

      - name: Vet
        run: go vet

      - name: Test
        run: go test ./...
